// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::driveMotorLeftFront = NULL;
SpeedController* RobotMap::driveMotorRightRear = NULL;
SpeedController* RobotMap::driveMotorRightFront = NULL;
SpeedController* RobotMap::driveMototLeftRear = NULL;
RobotDrive* RobotMap::driveRobotDrive = NULL;
Servo* RobotMap::cameraCameraVert = NULL;
Servo* RobotMap::cameraCameraHoriz = NULL;
SpeedController* RobotMap::elevatorSpeedController1 = NULL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	driveMotorLeftFront = new Talon(3);
	lw->AddActuator("Drive", "Motor Left Front", (Talon*) driveMotorLeftFront);
	
	driveMotorRightRear = new Talon(2);
	lw->AddActuator("Drive", "Motor Right Rear", (Talon*) driveMotorRightRear);
	
	driveMotorRightFront = new Talon(1);
	lw->AddActuator("Drive", "Motor Right Front", (Talon*) driveMotorRightFront);
	
	driveMototLeftRear = new Talon(4);
	lw->AddActuator("Drive", "Motot Left Rear", (Talon*) driveMototLeftRear);
	
	driveRobotDrive = new RobotDrive(driveMotorLeftFront, driveMototLeftRear,
              driveMotorRightFront, driveMotorRightRear);
	
	driveRobotDrive->SetSafetyEnabled(false);
        driveRobotDrive->SetExpiration(0.1);
        driveRobotDrive->SetSensitivity(0.5);
        driveRobotDrive->SetMaxOutput(1.0);

	cameraCameraVert = new Servo(5);
	lw->AddActuator("Camera", "CameraVert", cameraCameraVert);
	
	cameraCameraHoriz = new Servo(6);
	lw->AddActuator("Camera", "Camera Horiz", cameraCameraHoriz);
	
	elevatorSpeedController1 = new Talon(0);
	lw->AddActuator("Elevator", "Speed Controller 1", (Talon*) elevatorSpeedController1);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
